name: "match-tag-to-package-version"
description: "Makes sure that git tag and version in package.json match"
runs:
  using: "node18"
  main: "dist/index.js"
branding:
  icon: "tag"
  color: "yellow"
inputs:
  TAG_PREFIX:
    description: "Tag prefix used in git (eg. v)"
    required: false
outputs:
  PACKAGE_VERSION:
    description: "Version of the package (in package.json)"
  TAG_VERSION:
    description: "Version of the package in git"
